# Generated by Django 6.0 on 2026-01-12 03:16

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makhachhang', models.CharField(editable=False, max_length=15, unique=True)),
                ('tenkhachhang', models.CharField(max_length=255)),
                ('tenkhachhangkhongdau', models.CharField(blank=True, editable=False, max_length=255)),
                ('diachi', models.CharField(blank=True, max_length=500)),
                ('sdt', models.CharField(blank=True, max_length=20)),
                ('mst', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phanloai', models.CharField(choices=[('SI', 'Sỉ'), ('LE', 'Lẻ')], default='LE', max_length=2)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('no_dau_ky', models.DecimalField(decimal_places=0, default=0, help_text='Số nợ cũ trước khi dùng phần mềm', max_digits=15)),
                ('han_muc_no', models.DecimalField(decimal_places=0, default=0, help_text='Giới hạn nợ tối đa cho phép', max_digits=15)),
                ('ghichu', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDonHoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadonhoan', models.CharField(editable=False, max_length=50, unique=True)),
                ('trangthaiduyet', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('canceled', 'Hủy')], default='pending', max_length=10)),
                ('tongtienhoan', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('lydohoan', models.TextField(blank=True)),
                ('ngaylap', models.DateField(default=datetime.date.today)),
                ('ngayduyet', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('khachhang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoadon_hoan', to='app_quan_ly.khachhang')),
            ],
            options={
                'permissions': [('approve_hoadonhoan', 'Có thể duyệt đơn hoàn'), ('cancel_hoadonhoan', 'Có thể hủy đơn hoàn')],
            },
        ),
        migrations.CreateModel(
            name='HoaDonBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahoadonban', models.CharField(editable=False, max_length=50, unique=True)),
                ('chietkhauchung', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tongtienphaithanhtoan', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('khachhangungtien', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('trangthaidon', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('canceled', 'Hủy')], default='pending', max_length=10)),
                ('ghichu', models.TextField(blank=True)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngaylap', models.DateField(default=datetime.date.today)),
                ('ngaycapnhat', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('khachhang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoadon_ban', to='app_quan_ly.khachhang')),
            ],
            options={
                'permissions': [('approve_hoadonban', 'Có thể duyệt hóa đơn bán'), ('cancel_hoadonban', 'Có thể hủy hóa đơn bán')],
            },
        ),
        migrations.CreateModel(
            name='PhieuThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maphieuthu', models.CharField(editable=False, max_length=20, unique=True)),
                ('mahoadon', models.CharField(blank=True, max_length=20)),
                ('ngaylap', models.DateTimeField(auto_now_add=True)),
                ('sotienthu', models.DecimalField(decimal_places=0, max_digits=15)),
                ('hinhthucthanhtoan', models.CharField(default='Tiền mặt', max_length=100)),
                ('ghichu', models.TextField(blank=True)),
                ('trang_thai_duyet', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('canceled', 'Hủy')], default='pending', max_length=20)),
                ('khachhang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_quan_ly.khachhang')),
                ('nguoi_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_thu_da_lap', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('approve_phieuthu', 'Có thể duyệt phiếu thu'), ('cancel_phieuthu', 'Có thể hủy phiếu thu')],
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masanpham', models.CharField(editable=False, max_length=15, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('tensanpham', models.CharField(max_length=255)),
                ('tensanphamkhongdau', models.CharField(blank=True, editable=False, max_length=255)),
                ('donvitinh', models.CharField(max_length=50)),
                ('dongiagoc', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('dongiaban', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('tonkho', models.IntegerField(default=0)),
                ('ghichu', models.TextField(blank=True)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('ngaycapnhat', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang kinh doanh')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDonHoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensanpham', models.CharField(max_length=255)),
                ('donvitinh', models.CharField(max_length=50)),
                ('soluong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dongiagoc', models.DecimalField(decimal_places=0, max_digits=15)),
                ('dongialucban', models.DecimalField(decimal_places=0, max_digits=15)),
                ('chietkhau', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('thanhtien', models.DecimalField(decimal_places=0, max_digits=15)),
                ('ghichu', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hoadonhoan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet_hoan', to='app_quan_ly.hoadonhoan')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_quan_ly.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDonBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tensanpham', models.CharField(max_length=255)),
                ('donvitinh', models.CharField(blank=True, max_length=50, null=True)),
                ('soluong', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dongiagoc', models.DecimalField(decimal_places=0, max_digits=15)),
                ('dongiaban', models.DecimalField(decimal_places=0, max_digits=15)),
                ('chietkhau', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('thanhtien', models.DecimalField(decimal_places=0, max_digits=15)),
                ('ghichu', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hoadonban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet_ban', to='app_quan_ly.hoadonban')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_quan_ly.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='SoCaiCongNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_ghi_so', models.DateTimeField(auto_now_add=True)),
                ('ma_chung_tu', models.CharField(max_length=50)),
                ('dien_giai', models.CharField(max_length=255)),
                ('tang', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('giam', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('du_no_tuc_thoi', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('khachhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='so_no_rieng', to='app_quan_ly.khachhang')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ngay_ghi_so', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='khachhang',
            index=models.Index(fields=['tenkhachhangkhongdau'], name='app_quan_ly_tenkhac_14cde7_idx'),
        ),
        migrations.AddIndex(
            model_name='khachhang',
            index=models.Index(fields=['sdt'], name='app_quan_ly_sdt_53d1cf_idx'),
        ),
        migrations.AddIndex(
            model_name='khachhang',
            index=models.Index(fields=['makhachhang'], name='app_quan_ly_makhach_ac85f7_idx'),
        ),
        migrations.AddIndex(
            model_name='khachhang',
            index=models.Index(fields=['is_active'], name='app_quan_ly_is_acti_0b5bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonhoan',
            index=models.Index(fields=['mahoadonhoan'], name='app_quan_ly_mahoado_299d25_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonhoan',
            index=models.Index(fields=['khachhang', '-ngaylap'], name='app_quan_ly_khachha_a2a44c_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonhoan',
            index=models.Index(fields=['trangthaiduyet'], name='app_quan_ly_trangth_49c2a5_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonhoan',
            index=models.Index(fields=['-ngaylap'], name='app_quan_ly_ngaylap_b8b8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonban',
            index=models.Index(fields=['mahoadonban'], name='app_quan_ly_mahoado_b5e026_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonban',
            index=models.Index(fields=['khachhang', '-ngaylap'], name='app_quan_ly_khachha_c523d0_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonban',
            index=models.Index(fields=['trangthaidon'], name='app_quan_ly_trangth_caad40_idx'),
        ),
        migrations.AddIndex(
            model_name='hoadonban',
            index=models.Index(fields=['-ngaylap', '-ngaytao'], name='app_quan_ly_ngaylap_74aa54_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['tensanphamkhongdau'], name='app_quan_ly_tensanp_fb8c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['masanpham'], name='app_quan_ly_masanph_195822_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['barcode'], name='app_quan_ly_barcode_fb2d96_idx'),
        ),
        migrations.AddIndex(
            model_name='sanpham',
            index=models.Index(fields=['is_active'], name='app_quan_ly_is_acti_081a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='socaicongno',
            index=models.Index(fields=['khachhang', '-ngay_ghi_so', '-id'], name='app_quan_ly_khachha_2f7873_idx'),
        ),
        migrations.AddIndex(
            model_name='socaicongno',
            index=models.Index(fields=['ma_chung_tu'], name='app_quan_ly_ma_chun_ba6b6d_idx'),
        ),
    ]
