# Generated by Django 6.0.1 on 2026-01-07 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quan_ly', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='socaicongno',
            index=models.Index(fields=['khachhang', '-ngay_ghi_so', '-id'], name='app_quan_ly_khachha_2f7873_idx'),
        ),
        migrations.AddIndex(
            model_name='socaicongno',
            index=models.Index(fields=['ma_chung_tu'], name='app_quan_ly_ma_chun_ba6b6d_idx'),
        ),
    ]
