# Generated by Django 6.0.1 on 2026-01-09 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quan_ly', '0002_socaicongno_app_quan_ly_khachha_2f7873_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadonban',
            name='ngaylap',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
