# Generated by Django 6.0.1 on 2026-01-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quan_ly', '0002_create_groups_and_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieuthu',
            name='mahoadon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='phieuthu',
            name='maphieuthu',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
