# Generated by Django 6.0.1 on 2026-01-09 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quan_ly', '0003_hoadonban_ngaylap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadonhoan',
            name='ngaylap',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
